/** SEO uyumlu route path'leri */
export const ROUTES = {
  login: '/giris',
  home: '/',
  siparisYonetimi: '/siparis-yonetimi',
  urunler: '/urunler',
  urun: (id: string) => `/urunler/${id}`,
  tedarikciler: '/tedarikciler',
  tedarikci: (id: string) => `/tedarikciler/${id}`,
  personel: '/personel',
  musteriler: '/musteriler',
  musteri: (id: string) => `/musteriler/${id}`,
  bildirimler: '/bildirimler',
  teklifler: '/teklifler',
  teklifYeni: '/teklifler/yeni',
  teklifDuzenle: (id: string) => `/teklifler/${id}/duzenle`,
  teklif: (id: string) => `/teklifler/${id}`,
  satislar: '/satislar',
  satis: (id: string) => `/satislar/${id}`,
  satisYeni: '/satislar/yeni',
  servisTalepleri: '/servis-talepleri',
  servisTalebiYeni: '/servis-talepleri/yeni',
  servisTalebi: (id: string) => `/servis-talepleri/${id}`,
  gelirGider: '/gelir-gider',
  raporlar: '/raporlar',
  alislar: '/alislar',
  alis: (id: string) => `/alislar/${id}`,
  alisYeni: '/alislar/yeni',
  kullanicilar: '/kullanicilar',
  odemeAl: '/odeme-al',
  ayarlar: '/ayarlar',
  muhasebe: '/muhasebe',
  kasa: '/muhasebe/kasa',
  kasaDetay: (id: string) => `/muhasebe/kasa/${id}`,
  masrafCikisi: '/muhasebe/masraf-cikisi',
  tedarikciCari: '/muhasebe/tedarikci-cari',
  musteriCari: '/muhasebe/musteri-cari',
  mutabakatlar: '/muhasebe/mutabakatlar',
} as const;
